spring.application.name=demo

#localhost
#spring.kafka.bootstrap-servers=localhost:9092

#Production Docker Version
#spring.kafka.bootstrap-servers=kafka-local:9092
spring.kafka.bootstrap-servers=product-infra:9092